### ISSUE TITLE
Feature 1: User can start a game of blackjack

### ISSUE THREAD

**Issue by jsygo** [jsygo/blackjack#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start a game of blackjack.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click 'deal cards' button, and will be dealt two cards. the dealer will also receive two cards.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-22 at 10 39 25 AM](https://user-images.githubusercontent.com/87832078/134394358-f6629354-d6c7-4d0a-bef0-ebd661ef25f7.png)

![Screen Shot 2021-09-21 at 1 26 21 PM](https://user-images.githubusercontent.com/87832078/134242573-8a7ba81e-2555-41c5-9182-bbac4b466d5f.png)

![Screen Shot 2021-09-22 at 10 41 50 AM](https://user-images.githubusercontent.com/87832078/134394364-89e1c4cd-e31c-4f35-8bf7-9d6d12c58e64.png)

![Screen Shot 2021-09-21 at 1 30 26 PM](https://user-images.githubusercontent.com/87832078/134243118-11e80c35-cb06-4bd6-bcc8-7548a0af3d83.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a starting page.
- [x] Add background color for the body of the page.
- [x] Add the text on the table.
- [x] Add and style the 'deal cards' button.
- [x] Add empty divs for the players cards and for the dealers cards.
- [x] Add dummy data cards and make sure they display properly on both mobile and desktop.
- [x] Set up view swapping between starting page and game page.
- [x] Create a data model to hold the player and dealer hands.
- [x] Create a constructor function to create new player objects.
- [x] Make an XHR to create a new shuffled deck.
- [x] Add the current deck id to the data model.
- [x] Create a function to draw cards from the deck.
- [x] Create a function to deal drawn cards to player.
- [x] Deal cards to player and dealer when deal cards button is clicked.
- [x] Render cards in player and dealer hand on page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
