### ISSUE TITLE
Feature 2: User can hit

### ISSUE THREAD

**Issue by jsygo** [jsygo/blackjack#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hit.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click 'hit' button and will be dealt one card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 2 24 32 PM](https://user-images.githubusercontent.com/87832078/134249839-3de74d97-936a-4fce-82ea-4f6d1ea272cb.png)

![Screen Shot 2021-09-21 at 2 24 46 PM](https://user-images.githubusercontent.com/87832078/134249846-42142e9a-65ed-4b08-a2fe-9264f7cff3e8.png)

**Comment by jsygo** [comment]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Once deal cards button is clicked, hide deal cards button.
- [x] Create and style hit button.
- [x] Hide hit button until cards are dealt.
- [x] Deal one card to the player when hit button is clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
