### ISSUE TITLE
Feature 3: User can stand

### ISSUE THREAD

**Issue by jsygo** [jsygo/blackjack#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can stand.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click 'stand' button. The dealers face-down card will be revealed. If the dealers total is 16 or less, the dealer will be dealt a card. Once the dealers total is 17 or more, no more cards are dealt.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 2 35 54 PM](https://user-images.githubusercontent.com/87832078/134251033-7a6455c6-b579-4bde-8116-159bf50ea244.png)

![Screen Shot 2021-09-21 at 2 35 41 PM](https://user-images.githubusercontent.com/87832078/134251052-f4375a06-9bf9-47df-abe6-3a496875a934.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create stand button.
- [x] Space out hit and stand button properly on both mobile and desktop.
- [x] Display the second card of the dealers hand as face down.
- [x] Once stand button is clicked, display the front of that card.
- [x] Define a function to check the score of the player or dealers hand.
  - [x] Create conditional to check what the value of an ace should be.
- [x] When stand button is clicked, if the dealers score is 16 or less, have the dealer hit until the dealers score is at least 17.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
