### ISSUE TITLE
Feature 4: User can complete a game

### ISSUE THREAD

**Issue by jsygo** [jsygo/blackjack#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can complete a game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the dealer stands, a modal appears showing the players score, the dealers score, and the outcome of the game.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 2 44 00 PM](https://user-images.githubusercontent.com/87832078/134251975-7a061a85-2340-4174-8b28-a6231e2409eb.png)

![Screen Shot 2021-09-21 at 2 44 22 PM](https://user-images.githubusercontent.com/87832078/134251997-23d3cba7-3717-4348-be9f-e8370f67c2d4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create modal for end of game.
- [x] Make sure modal displays properly on both mobile and desktop.
- [x] Modify hitStandHandler so that if the player busts, they automatically stand.
- [x] Modify text content of the end of game modal based on the player and dealer's scores.
- [x] Display modal once dealer stands.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
