### ISSUE TITLE
Feature 5: User can place bets

### ISSUE THREAD

**Issue by jsygo** [jsygo/blackjack#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can place bets.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User has a starting balance to bet with. Before dealing cards at the start of the game, user can place a bet up to the amount they hold in their balance. If the user wins the hand, they receive 1.5 x their bet. If the user loses the hand, they lose the money that they bet.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create play again button.
- [x] Style play again button.
- [x] Make sure end of game modal still displays properly on desktop and mobile.
- [x] Create balance and current bet and add to page.
- [x] Make sure balance and current bet display properly on both mobile and desktop.
- [x] Create input and buttons for placing bet at beginning of the game.
- [x] Make sure input and buttons for placing bet display properly on both mobile and desktop.
- [x] Add a balance property to the new Player constructor function.
- [x] Add a previous hands property to the new Player constructor function.
- [x] Add a current bet property to the data model.
- [x] Modify balance and current bet in data model based on user input on the bet form.
- [x] Modify text of balance and current bet based on the data from the data model.
- [x] Once player places a bet and deals the cards, hide the betting view.
- [x] If player wins, add their winnings to their balance. If player gets blackjack, multiply winnings by 1.5.
- [x] Create a constructor function for a previous hand object with a player hand, dealer hand, and bet property.
- [x] When play again button is clicked, reset to the initial betting view.
  - [x] Create new previous hand object with data from the current hand, and add it to the previous hands property of the current player.
  - [x] Clear player and dealer hands.
  - [x] Show the betting input and buttons again.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
